#!/usr/bin/env bash
# Apply a colour theme across every app that has a palette.
#
# Usage: theme_apply.sh <theme-name> [--no-reload]
#        theme_apply.sh --list
#
# Reads one JSON from ~/.config/hypr/themes/ and writes a small generated file
# per app. Every generated file is a sidecar the app already includes, so the
# hand-written config keeps its layout and only the colours move.
#
# Adding an app means adding one heredoc below. Adding a theme means dropping a
# JSON in themes/ with the same keys as the others.

set -euo pipefail

THEME_DIR="$HOME/.config/hypr/themes"
STATE_FILE="${XDG_STATE_HOME:-$HOME/.local/state}/current-theme"

list_themes() {
    for f in "$THEME_DIR"/*.json; do
        [ -e "$f" ] || continue
        printf '  %-18s %s\n' "$(basename "$f" .json)" "$(jq -r '._meta.name // ""' "$f")"
    done
}

mode="${1:-}"
skip_reload="${2:-}"

if [ -z "$mode" ] || [ "$mode" = "--list" ] || [ "$mode" = "-h" ]; then
    echo "Usage: theme_apply.sh <theme-name> [--no-reload]"
    echo "Available themes:"
    list_themes
    [ -f "$STATE_FILE" ] && echo "Current: $(cat "$STATE_FILE")"
    exit 0
fi

SRC="$THEME_DIR/${mode}.json"
if [ ! -f "$SRC" ]; then
    echo "Unknown theme '$mode'. Available:" >&2
    list_themes >&2
    exit 1
fi

command -v jq >/dev/null || { echo "jq is required" >&2; exit 1; }

g() { jq -r ".$1 // empty" "$SRC"; }

BASE=$(g base);         MANTLE=$(g mantle);     CRUST=$(g crust)
TEXT=$(g text);         SUBTEXT0=$(g subtext0); SUBTEXT1=$(g subtext1)
SURFACE0=$(g surface0); SURFACE1=$(g surface1); SURFACE2=$(g surface2)
OVERLAY0=$(g overlay0); OVERLAY1=$(g overlay1); OVERLAY2=$(g overlay2)

BLUE=$(g blue);   SAPPHIRE=$(g sapphire); PEACH=$(g peach); GREEN=$(g green)
RED=$(g red);     MAUVE=$(g mauve);       PINK=$(g pink);   YELLOW=$(g yellow)
MAROON=$(g maroon); TEAL=$(g teal)

ACCENT=$(g accent);               ACCENT=${ACCENT:-$BLUE}
ACCENT_DIM=$(g accent_dim);       ACCENT_DIM=${ACCENT_DIM:-$SAPPHIRE}
ACCENT_BRIGHT=$(g accent_bright); ACCENT_BRIGHT=${ACCENT_BRIGHT:-$TEAL}
SELECTION=$(g selection);         SELECTION=${SELECTION:-$SURFACE1}
BORDER=$(g border);               BORDER=${BORDER:-$SURFACE2}

# Terminal 16, falling back to the main palette where a theme omits one.
TB=$(g term_black);   TB=${TB:-$SURFACE1}
TR=$(g term_red);     TR=${TR:-$RED}
TG=$(g term_green);   TG=${TG:-$GREEN}
TY=$(g term_yellow);  TY=${TY:-$YELLOW}
TBL=$(g term_blue);   TBL=${TBL:-$BLUE}
TMA=$(g term_magenta); TMA=${TMA:-$PINK}
TC=$(g term_cyan);    TC=${TC:-$TEAL}
TW=$(g term_white);   TW=${TW:-$SUBTEXT0}
TBB=$(g term_bright_black);   TBB=${TBB:-$SURFACE2}
TBR=$(g term_bright_red);     TBR=${TBR:-$RED}
TBG=$(g term_bright_green);   TBG=${TBG:-$GREEN}
TBY=$(g term_bright_yellow);  TBY=${TBY:-$YELLOW}
TBBL=$(g term_bright_blue);   TBBL=${TBBL:-$BLUE}
TBM=$(g term_bright_magenta); TBM=${TBM:-$PINK}
TBC=$(g term_bright_cyan);    TBC=${TBC:-$TEAL}
TBW=$(g term_bright_white);   TBW=${TBW:-$TEXT}

RAD_L=$(g radius_large); RAD_L=${RAD_L:-14}

# Strip the leading # for the formats that want bare hex.
s() { echo "${1#\#}"; }

# #rrggbb to "r, g, b" for CSS rgba().
hex2rgb() {
    local h="${1#\#}"
    printf "%d, %d, %d" "0x${h:0:2}" "0x${h:2:2}" "0x${h:4:2}"
}

w() { mkdir -p "$(dirname "$1")"; cat > "$1"; }

# GTK apps: a colors.css sidecar next to style.css. These load their stylesheet
# from a path, so a relative @import resolves against the stylesheet directory.
GTK_COLORS="@define-color bg_base ${BASE};
@define-color bg_mantle ${MANTLE};
@define-color bg_crust ${CRUST};
@define-color bg_surface0 ${SURFACE0};
@define-color bg_surface1 ${SURFACE1};
@define-color bg_surface2 ${SURFACE2};
@define-color text_primary ${TEXT};
@define-color text_secondary ${SUBTEXT0};
@define-color text_muted ${SUBTEXT1};
@define-color overlay0 ${OVERLAY0};
@define-color overlay1 ${OVERLAY1};
@define-color overlay2 ${OVERLAY2};
@define-color accent ${ACCENT};
@define-color accent_dim ${ACCENT_DIM};
@define-color accent_bright ${ACCENT_BRIGHT};
@define-color blue ${BLUE};
@define-color sapphire ${SAPPHIRE};
@define-color green ${GREEN};
@define-color red ${RED};
@define-color yellow ${YELLOW};
@define-color peach ${PEACH};
@define-color mauve ${MAUVE};
@define-color pink ${PINK};
@define-color maroon ${MAROON};
@define-color teal ${TEAL};
@define-color selection ${SELECTION};
@define-color border_subtle rgba($(hex2rgb "$BORDER"), 0.6);"

for app in waybar swaync wlogout nwg-dock-hyprland; do
    [ -d "$HOME/.config/$app" ] || continue
    printf '/* Generated by theme_apply.sh. Do not edit. */\n%s\n' "$GTK_COLORS" \
        > "$HOME/.config/$app/colors.css"
done

# wofi builds its stylesheet with load_from_data, which has no base path, so an
# @import cannot resolve. Its stylesheets are generated whole instead: the stowed
# templates/ hold the rules, and the colours get prepended on the way out.
WOFI_COLORS="@define-color bg_base ${BASE};
@define-color bg_mantle ${MANTLE};
@define-color bg_crust ${CRUST};
@define-color bg_surface0 ${SURFACE0};
@define-color bg_surface1 ${SURFACE1};
@define-color text_primary ${TEXT};
@define-color overlay2 ${OVERLAY2};
@define-color accent ${ACCENT};
@define-color red ${RED};
@define-color pink ${PINK};
@define-color selection ${SELECTION};"

for t in "$HOME"/.config/wofi/templates/*.css; do
    [ -e "$t" ] || continue
    {
        echo "/* Generated by theme_apply.sh from templates/. Do not edit. */"
        echo "$WOFI_COLORS"
        echo
        cat "$t"
    } > "$HOME/.config/wofi/$(basename "$t")"
done

# Hyprland, read by theme.lua.
w "$HOME/.config/hypr/colors.lua" <<EOF
-- Generated by theme_apply.sh. Do not edit.
return {
    bg              = "rgb($(s "$BASE"))",
    mantle          = "rgb($(s "$MANTLE"))",
    crust           = "rgb($(s "$CRUST"))",
    surface0        = "rgb($(s "$SURFACE0"))",
    surface1        = "rgb($(s "$SURFACE1"))",
    text            = "rgb($(s "$TEXT"))",
    accent          = "rgb($(s "$ACCENT"))",
    border          = "rgba($(s "$ACCENT")ff)",
    border_inactive = "rgba($(s "$CRUST")aa)",
    red             = "rgb($(s "$RED"))",
    green           = "rgb($(s "$GREEN"))",
    yellow          = "rgb($(s "$YELLOW"))",
    blue            = "rgb($(s "$BLUE"))",
    mauve           = "rgb($(s "$MAUVE"))",
    rounding        = ${RAD_L},
}
EOF

# hyprlock, sourced by hyprlock.conf.
w "$HOME/.config/hypr/hyprlock-colors.conf" <<EOF
# Generated by theme_apply.sh. Do not edit.
\$lock_text = rgba($(s "$TEXT")ee)
\$lock_text_dim = rgba($(s "$SUBTEXT0")cc)
\$lock_ring = rgb($(s "$OVERLAY2"))
\$lock_ring_check = rgb($(s "$GREEN"))
\$lock_ring_fail = rgb($(s "$RED"))
\$lock_bg = rgba($(s "$CRUST")ff)
EOF

# ghostty, pulled in by a config-file line.
w "$HOME/.config/ghostty/colors" <<EOF
# Generated by theme_apply.sh. Do not edit.
background = $(s "$BASE")
foreground = $(s "$TEXT")
cursor-color = $(s "$ACCENT")
cursor-text = $(s "$BASE")
selection-background = $(s "$SELECTION")
selection-foreground = $(s "$TEXT")
palette = 0=$(s "$TB")
palette = 1=$(s "$TR")
palette = 2=$(s "$TG")
palette = 3=$(s "$TY")
palette = 4=$(s "$TBL")
palette = 5=$(s "$TMA")
palette = 6=$(s "$TC")
palette = 7=$(s "$TW")
palette = 8=$(s "$TBB")
palette = 9=$(s "$TBR")
palette = 10=$(s "$TBG")
palette = 11=$(s "$TBY")
palette = 12=$(s "$TBBL")
palette = 13=$(s "$TBM")
palette = 14=$(s "$TBC")
palette = 15=$(s "$TBW")
EOF

# kitty, included from kitty.conf line 1.
if [ -d "$HOME/.config/kitty" ]; then
    w "$HOME/.config/kitty/current-theme.conf" <<EOF
# Generated by theme_apply.sh. Do not edit.
background ${BASE}
foreground ${TEXT}
cursor ${ACCENT}
color0  ${TB}
color1  ${TR}
color2  ${TG}
color3  ${TY}
color4  ${TBL}
color5  ${TMA}
color6  ${TC}
color7  ${TW}
color8  ${TBB}
color9  ${TBR}
color10 ${TBG}
color11 ${TBY}
color12 ${TBBL}
color13 ${TBM}
color14 ${TBC}
color15 ${TBW}
EOF
fi

# alacritty, imported by alacritty.toml.
if [ -d "$HOME/.config/alacritty" ]; then
    w "$HOME/.config/alacritty/themes/current.toml" <<EOF
# Generated by theme_apply.sh. Do not edit.
[colors.primary]
background = '${BASE}'
foreground = '${TEXT}'

[colors.cursor]
text = '${BASE}'
cursor = '${ACCENT}'

[colors.normal]
black = '${TB}'
red = '${TR}'
green = '${TG}'
yellow = '${TY}'
blue = '${TBL}'
magenta = '${TMA}'
cyan = '${TC}'
white = '${TW}'

[colors.bright]
black = '${TBB}'
red = '${TBR}'
green = '${TBG}'
yellow = '${TBY}'
blue = '${TBBL}'
magenta = '${TBM}'
cyan = '${TBC}'
white = '${TBW}'
EOF
fi

mkdir -p "$(dirname "$STATE_FILE")"
echo "$mode" > "$STATE_FILE"

if [ "$skip_reload" = "--no-reload" ]; then
    echo "Wrote $mode. Reload skipped."
    exit 0
fi

# Reload. Each app is optional, so a missing one is not an error.
hyprctl reload >/dev/null 2>&1 || true
pkill -x kitty -USR1 2>/dev/null || true

# waybar and swaync only re-read CSS on start.
for app in waybar swaync; do
    if pgrep -x "$app" >/dev/null 2>&1; then
        pkill -x "$app" || true
        # swaync aborts if it grabs its dbus name before the old one lets go.
        sleep 1
        setsid "$app" </dev/null >/dev/null 2>&1 &
    fi
done

if pgrep -x nwg-dock-hyprla >/dev/null 2>&1; then
    pkill -x nwg-dock-hyprla || true
    sleep 0.3
    setsid nwg-dock-hyprland -i 32 -nolauncher -l top -p bottom -o eDP-1 \
        </dev/null >/dev/null 2>&1 &
fi

notify-send -a "Theme" "Theme applied" "$(jq -r '._meta.name // empty' "$SRC")" 2>/dev/null || true
echo "Applied $mode."
