include current-theme.conf

shell /bin/zsh --login --interactive

font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 10.0

cursor_shape beam
cursor_blink_interval 0.5

window_padding_width 10

background_opacity 0.75

map ctrl+backspace send_text all \x1b[127;5u
map alt+backspace send_text all \x1b[127;3u

# Zoom keybindings
map ctrl+equal change_font_size all +1.0
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0
