#!/bin/bash
# Regenerate espanso/match/prompts.yml from claude-config/prompts/*.md
# Each prompt with a :trigger: frontmatter field gets an espanso match.
# Prompts without :trigger: are skipped.
# Usage: bash arch/scripts/sync-espanso-from-prompts.sh
# Run after editing any prompt file.

set -eu

# Script lives at arch/scripts/, repo root is two levels up
DOTFILES_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
PROMPTS_DIR="$DOTFILES_DIR/claude-config/prompts"
OUT="$DOTFILES_DIR/claude-config/espanso/match/prompts.yml"

mkdir -p "$(dirname "$OUT")"

# Hardcoded trigger map: prompt_name -> espanso_trigger
# Edit this to add/remove triggers without touching the prompt files.
declare -A TRIGGERS=(
  [debug]=":pdebug"
  [review-diff]=":previewdiff"
  [adr]=":padr"
  [rubber-duck]=":prubber"
  [apa7-cite]=":papa"
)

cat > "$OUT" <<'HEADER'
# Auto-generated by arch/scripts/sync-espanso-from-prompts.sh
# Do not edit manually. Edit the source prompts in claude-config/prompts/.
matches:
HEADER

for name in "${!TRIGGERS[@]}"; do
  trigger="${TRIGGERS[$name]}"
  src="$PROMPTS_DIR/$name.md"

  if [[ ! -f "$src" ]]; then
    echo "WARN: $src not found, skipping trigger $trigger" >&2
    continue
  fi

  # Strip YAML frontmatter (everything between first and second --- lines)
  body=$(awk '/^---$/{n++; if(n==2){found=1; next}} found{print}' "$src")

  if [[ -z "$body" ]]; then
    echo "WARN: $src has no body after frontmatter, skipping" >&2
    continue
  fi

  printf '  - trigger: "%s"\n' "$trigger" >> "$OUT"
  printf '    replace: |\n' >> "$OUT"
  while IFS= read -r line; do
    printf '      %s\n' "$line" >> "$OUT"
  done <<< "$body"
  printf '\n' >> "$OUT"
done

echo "Wrote $OUT with ${#TRIGGERS[@]} triggers."
echo "Symlink: ln -sf \"$OUT\" ~/.config/espanso/match/prompts.yml"
echo "Reload:  espanso restart"
