-- Theme colours for the Hyprland config.
--
-- colors.lua is generated by scripts/theme-apply.sh and is gitignored. It is
-- loaded defensively: a missing or broken colors.lua falls back to the palette
-- below rather than taking the whole config down, which is what happens when a
-- colour variable ends up unset.
--
-- The fallback is the palette the config shipped with (Catppuccin Mocha, plus
-- the blue borders), so a machine that has never run theme-apply.sh looks
-- exactly as it did before the theme engine existed.

local fallback = {
    bg              = "rgb(1e1e2e)",
    mantle          = "rgb(181825)",
    crust           = "rgb(11111b)",
    surface0        = "rgb(313244)",
    surface1        = "rgb(45475a)",
    text            = "rgb(cdd6f4)",
    accent          = "rgb(89b4fa)",
    border          = "rgba(65b2ffff)",
    border_inactive = "rgba(011423aa)",
    red             = "rgb(f38ba8)",
    green           = "rgb(a6e3a1)",
    yellow          = "rgb(f9e2af)",
    blue            = "rgb(89b4fa)",
    mauve           = "rgb(cba6f7)",
    rounding        = 14,
}

local theme = {}
for k, v in pairs(fallback) do
    theme[k] = v
end

local ok, generated = pcall(require, "colors")
if ok and type(generated) == "table" then
    for k, v in pairs(generated) do
        theme[k] = v
    end
end

-- Global so every required file can reach it without each one repeating the
-- pcall. Hyprland scopes require() per file.
Theme = theme

return theme
