# Arch zsh config. Everything shared lives in ~/.config/zsh/shared.zsh.

# p10k instant prompt, must stay at the top.
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export BROWSER=librewolf
export GH_CONFIG_DIR="$HOME/.config/gh"

source ~/.config/zsh/shared.zsh

alias update='sudo pacman -Syyu && paru && hyprpm update'
alias refreshmirrors='rate-mirrors arch | sudo tee /etc/pacman.d/mirrorlist'
alias pkgfnd='pacman -Q | grep'
alias performance='sudo cpupower frequency-set -g performance'
alias serialfix='sudo chmod +766 /dev/ttyACM0'
alias ports='netstat -tulanp'
alias cpufetch='cpufetch --style fancy --color 230,50,45:240,230,230:0,0,0:250,70,65:170,170,170'
alias gpt='chatgpt.sh -cc'

dnsfix() {
    sudo tee /etc/resolv.conf > /dev/null <<'EOF'
# Generated by NetworkManager
search home
nameserver 1.1.1.1
options edns0 trust-ad
EOF
}
sunshine_start() { DISPLAY=:1 sunshine; }
