set -g default-terminal "tmux-256color"
set -g display-panes-time 5000
set-option -ga terminal-overrides ",xterm-256color:RGB"

# Pass CSI-u key sequences (ctrl+backspace etc from ghostty) through to zsh
set -s extended-keys always
set -as terminal-features 'xterm-ghostty:extkeys'

unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

set -g mouse on

source-file -q ~/.tmux.local.conf

bind r run "sh -c 'tmux source ~/.config/tmux/tmux.conf'" \; display "#{TMUX_CONF} sourced"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind > swap-pane -D
bind < swap-pane -U

unbind n
unbind p
bind -r C-h previous-window
bind -r C-l next-window

set -g base-index 1
setw -g pane-base-index 1

setw -g automatic-rename on
set -g renumber-windows on

set -g monitor-activity on
set -g visual-activity off

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'niksingh710/minimal-tmux-status'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

set -g @resurrect-strategy-nvim 'session'

bind -r H resize-pane -L 25
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 25

run '~/.tmux/plugins/tpm/tpm'
